<template>
  <div class="loadingio-spinner-bars-gjgi3ppizbo">
    <div class="ldio-igtowwqpygc">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<script>
export default {

}
</script>

<style type="text/css">
.loadingio-spinner-bars-gjgi3ppizbo {
  opacity: 1;
  z-index: 1000;
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  width: 100vw;
  height: 100vh;
  display: inline-block;
  overflow: hidden;
  background: none;
  background: #00000055;
  transition: opacity 100ms ease-in-out;
}
.loadingio-spinner-bars-gjgi3ppizbo.fade-out {
  opacity: 0;
  pointer-events: none;
}
.loadingio-spinner-bars-gjgi3ppizbo.isDark {
  background: #00000055;
}
.ldio-igtowwqpygc {
  width: 94px;
  height: 94px;
  left: 0;
  right: 0;
  margin: auto;
  position: absolute;
  top: 30vh;

  transform: translateZ(0) scale(0.94);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-igtowwqpygc div {
  box-sizing: content-box;
}
@keyframes ldio-igtowwqpygc {
  0% {
    opacity: 1;
  }
  50% {
    opacity: 0.2;
  }
  100% {
    opacity: 1;
  }
}
.ldio-igtowwqpygc div {
  position: absolute;
  width: 5px;
  height: 40px;
  top: 30px;
  animation: ldio-igtowwqpygc 0.7246376811594202s cubic-bezier(0.5, 0, 0.5, 1)
    infinite;
}
.ldio-igtowwqpygc div:nth-child(1) {
  transform: translate(17.5px, 0);
  background: #ffffff99;
  animation-delay: -0.4347826086956521s;
}
.ldio-igtowwqpygc div:nth-child(2) {
  transform: translate(37.5px, 0);
  background: #ffffff99;
  animation-delay: -0.2898550724637681s;
}
.ldio-igtowwqpygc div:nth-child(3) {
  transform: translate(57.5px, 0);
  background: #ffffff99;
  animation-delay: -0.14492753623188406s;
}
.ldio-igtowwqpygc div:nth-child(4) {
  transform: translate(77.5px, 0);
  background: #ffffff99;
  animation-delay: -0.7246376811594202s;
}
/* generated by https://loading.io/ */
</style>
